### ISSUE TITLE
Page not pushed or replaced if on the same path pattern

### ISSUE THREAD

**Issue by bdremynoel** [tomgilder/routemaster#142] opened 2021-06-11 13:44 UTC
Given this fragment `/detail/:id/equipment/:eqId`.
I need to loop over this path with `eqId` change.

Route is correctly matched and returns the page with correct args but the page nevers shows.

Also navigation is broken after this. pop doesn't pop to '/detail/:id' but to '/'.

**Comment by tomgilder** [comment] 2021-06-12 06:11
Hello, thanks for the report. 

Just to check, do you mean navigating from `/detail/1/equipment/2` to `/detail/1/equipment/3`?

**Comment by bdremynoel** [comment] 2021-06-12 17:03
yes absolutely. Once I'm on `/detail/1/equipment/2` I can't get to `/detail/1/equipment/3`.

**Comment by tomgilder** [comment] 2021-06-12 19:49
Any chance of a small reproduction case? This routing has worked when I've tested it.

Are you using custom page types? Implementing those incorrectly can cause routing to basically lock up like you describe.

**Comment by bdremynoel** [comment] 2021-06-12 20:35
No I'm using `MaterialPage`.
I think I overly simplified the case.

I'll try to provide similar routing aside of my app, in the meantime, here's my real routing for the current case.
For additional info I just found that after triggering '/ei/:eiId/eq/:eqId', '/' is called too so '/ei/:eiId' because of redirection. Maybe it's relevant.

```
'/': (route) {
  final id = I.get<AppContextBloc>().getBuilding()!.id;
  return Redirect('/ei/$id');
},
// Building global page
'/ei/:eiId': (route) {
  final eiId = RouteParam.asInt(route.pathParameters['eiId']!);

  return (eiId != null)
      ? TabPage(
          child: BuildingPage(buildingId: eiId),
          paths: [
            'hlr',
          ],
        ) as Page<dynamic>
      : NotFound();
},
'/ei/:eiId/hlr/edit': (route) {
  final eiId = RouteParam.asInt(route.pathParameters['eiId']!);
  final ids = RouteParam.asIntList(route.queryParameters['ids']);
  final index = RouteParam.asInt(route.queryParameters['index']);

  return (eiId != null && ids != null && ids.isNotEmpty)
      ? MaterialPage(child: HLRequestPaginatedEditPage(requestsId: ids, initialPage: index ?? 0))
      : NotFound();
},
'/ei/:eiId/eq/:eqId': (route) {
  final eiId = RouteParam.asInt(route.pathParameters['eiId']!);
  final eqId = RouteParam.asInt(route.pathParameters['eqId']!);
  final fromEqId = RouteParam.asInt(route.queryParameters['fromEqId']);

  return (eiId != null && eqId != null)
      ? MaterialPage(child: EquipmentDetailsPage(equipmentId: eqId, fromEquipmentId: fromEqId))
      : NotFound();
},
```

**Comment by bdremynoel** [comment] 2021-06-13 16:14
Here the reproducer.
[tab_routing.zip](https://github.com/tomgilder/routemaster/files/6644246/tab_routing.zip)

**Comment by tomgilder** [comment] 2021-06-14 15:17
Thanks for the example, am investigating

**Comment by tomgilder** [comment] 2021-06-14 15:27
The button "Goto another equipment" always tries to navigate to the same path due to you creating a new `Random` object every time.

Doing something like this fixes the part of the navigation:

```dart
class HlrEditPage extends StatelessWidget {
  const HlrEditPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar:
          AppBar(title: Text(Routemaster.of(context).currentRoute.fullPath)),
      body: Center(
        child: ElevatedButton(
            child: Text('Goto equipment'),
            onPressed: () {
              Routemaster.of(context).push('/ei/1/eq/1');
            }),
      ),
    );
  }
}

class EquipmentPage extends StatelessWidget {
  const EquipmentPage({Key? key}) : super(key: key);

  static int _value = 2;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar:
          AppBar(title: Text(Routemaster.of(context).currentRoute.fullPath)),
      body: Center(
        child: ElevatedButton(
            child: Text('Goto another equipment'),
            onPressed: () {
              Routemaster.of(context).push('/ei/1/eq/${_value++}');
            }),
      ),
    );
  }
}
```

But can confirm the navigation locking up, which is due to the tab index being set to the wrong value. Looking into it.

**Comment by bdremynoel** [comment] 2021-06-14 16:46
Sorry for the typo.
I've added a ValueKey to the equipment page which does help to navigate to dependent equipments on my project.

I'll wait for the fix to ensure thoses pages are correctly stacked.
'/ei/1/eq/1' => '/ei/1/eq/2' which is an additional symptom for me.

**Comment by tomgilder** [comment] 2021-06-14 17:45
Ahh yes, this might actually be Flutter not recognising a page change without a key.

Sorry, what do you mean by "ensure pages are correctly stacked"? What's not being correctly stacked, or do you mean the tab issue?

**Comment by bdremynoel** [comment] 2021-06-14 18:12
Don't know if it's related, I haven't had time to dig in.
The intermediate pages are wiped too when popping the last page.

Here's an updated the reproducer:
[tab_routing.zip](https://github.com/tomgilder/routemaster/files/6650384/tab_routing.zip)

If you pop the last equipment page, edit page and every equipment pages are gone. Those pages are not nested in `hlr` tab.

This is why I don't know if the pages are correctly stacked in this case.

**Comment by tomgilder** [comment] 2021-06-14 19:50
@bdremynoel found the problem - fix coming soon 👍

**Comment by tomgilder** [comment] 2021-06-14 21:31
@bdremynoel just published 0.9.4-dev1 on pub.dev, can you confirm if it fixes the tab issue (where navigation apparently locks up)?

**Comment by bdremynoel** [comment] 2021-06-14 22:09
I'd say yes! 🎉 

But... there's a behaviour change to notice.
I use `TabPage` with `TabBarView`. If I call a tab with query parameters from 'somewhere', the url now stays.
I just don't know how to reset this when activating tab from `BottomNavigationBar`.

Here's the code for now:

```dart
Scaffold(
  body: TabBarView(
    controller: tabState.controller,
    physics: NeverScrollableScrollPhysics(),
    children: [for (final stack in tabState.stacks) PageStackNavigator(stack: stack)],
   ),
   bottomNavigationBar: _BottomMenuBar(
     tabController: _tabMenuController,
     onTabSelected: (index) {
       tabState.controller.animateTo(index);
     },
)
```

**Comment by tomgilder** [comment] 2021-06-17 07:19
@bdremynoel great, closing this now - I think everything's fixed?

Let me know if there's another issue I've missed

**Closed by tomgilder** 2021-06-17 07:19 UTC

**Comment by bdremynoel** [comment] 2021-06-17 07:26
Everything is great on my side now.
Sorry for the fuzzy initial description.

Thanks!

**Comment by M4RZB4Ni** [comment] 2021-07-29 16:25
Hi,
I used your library for my project
and have this issue too.
how it must be fixed?

**Comment by tomgilder** [comment] 2021-07-29 16:36
Hi @M4RZB4Ni, given this particular issue has been fixed and released, your problem is probably a different one.

Please open a new issue with details of your problem, preferably with small example code of your problem.

**Comment by M4RZB4Ni** [comment] 2021-07-29 20:20
I was created issue but no one answered
