### ISSUE TITLE
TabPage navigation

### ISSUE THREAD

**Issue by bdremynoel** [tomgilder/routemaster#150] opened 2021-06-24 11:05 UTC
Here's the related routing for the current issue.

```dart
// A tab page , as my main page
'/ei/:eiId': (route) {
 return TabPage(..., paths: [..., 'list'])
}
// Nested page from tab page
'/ei/:eiId/list': (route) {
 return MaterialPage(...)
}
// A full page
'/ei/:eiId/sub/sub/:anotherId': (route) {
 return MaterialPage(...)
}
```
Route '/ei/:eiId/sub/sub/:anotherId' pushes '/ei/:eiId/list'.

~~When~~ **Land~~ing~~ directly** on '/ei/:eiId/sub/sub/:anotherId'~~, route '/ei/:eiId' is not build "completely" before this page, I can see it with inherited theme not applied.~~
When route '/ei/:eiId/list' is pushed, the URL is fine but the TabPage is broken, the listing tab doesn't show and tab navigation does not work.
If I refresh the page, the navigation gets back to normal and I get the listing page.

I just tried to wrap TabPage with StackPage in 0.10, but this does not change the behaviour.

For now, I must manually push '/ei/:eiId', wait few milliseconds, and replace with the listing page.

**Comment by tomgilder** [comment] 2021-06-24 20:53
Hello, can you clarify what you mean by the route not being "completely" built? Really not understanding that, sorry.

I've tried to reproduce a problem using the same route map but haven't been able to.

**Comment by bdremynoel** [comment] 2021-06-25 08:55
Here's an unperfect reproducer for the issue:
[tab_routing.zip](https://github.com/tomgilder/routemaster/files/6714812/tab_routing.zip)

You must ensure to land directly on http://localhost:<port>/#/ei/1/eq/1 to reproduce it (refresh page if necessary).
From there, go to list from the button.

=> You should get the HLR tab selected, the correct URL in bar address but the tab content is 'news'.

Out of interest, this is an unperfect reproducer since the tab page can be recovered by tapping on hlr bottom menu button.
In my project, I replace the navigation each time I tap on bottom menu item to reset query parameters, I cannot navigate anymore in this situation without refreshing the page. (which is not doable on other platforms).

**Comment by tomgilder** [comment] 2021-06-29 10:41
Thanks, I've reproduced it, will get to this as soon as I can

**Comment by bdremynoel** [comment] 2021-06-29 11:03
Thanks for the feedback!

**Comment by tomgilder** [comment] 2021-07-09 15:30
Apologises for not getting to this yet, have been very busy.

This issue is my top priority to fix, but in doing so I found another bug in Routemaster and another two bugs in Flutter itself 🤦

**Comment by llfbandit** [comment] 2021-07-09 15:51
Ahah! No worries, I've some workarounds.

Take your time to do it right. Routing is crucial in apps, for the feature it provides and also because it's like a "ghost" in the source code. We must trust the package at all costs.

I choose you mainly because of serious testing! Your comment resonates like an additional insurance to me!

**Comment by tomgilder** [comment] 2021-07-10 09:17
Thank you, that means a lot 😁 

I filed the first Flutter bug on this - this could also affect you given your app's structure: https://github.com/flutter/flutter/issues/86222

**Comment by tomgilder** [comment] 2021-07-10 14:48
Hi @llfbandit, in fact... I think it is that Flutter bug that you're seeing here.

Do you see this in Chrome's Console when running your app?

```
Error: Unexpected null value.
    at Object.throw_ [as throw] (errors.dart:236)
    at Object.nullCheck (operations.dart:518)
    at page_view._PagePosition.new.get viewportDimension [as viewportDimension] (scroll_position.dart:172)
    at page_view._PagePosition.new.getPixelsFromPage (page_view.dart:382)
    at page_view.PageController.new.animateToPage (page_view.dart:197)
    at tabs$._TabBarViewState.new._warpToCurrentIndex (tabs.dart:1417)
```

**Comment by bdremynoel** [comment] 2021-07-10 15:49
Hmm, I don't remember this trace. I'm now on vacation and won't be able to confirm this until end of July

**Comment by tomgilder** [comment] 2021-07-10 16:20
Cool, have a lovely vacation! 🌴 

Almost certain this is an upstream Flutter bug, sadly.

I'll have a think if I can come up with any workaround in Routemaster, but I doubt it. For now the easiest fix is probably copying `TabBarView` and doing a local fix.

**Comment by tomgilder** [comment] 2021-07-18 14:16
Here's a dirty hack you can try that might fix the issue.

Check `TickerMode.of(context)` and if it's `false`, don't return `TabBarView`:

```dart
Widget build(BuildContext context) {
  if (!TickerMode.of(context)) {
    return SizedBox();
  }

  return TabBarView(
    controller: TabPage.of(context).controller,
    children: [
      Scaffold(body: Text('One')),
      Scaffold(body: Text('Two')),
    ],
  );
}
```

This stops the `TabBarView` being rendered until the page is actually shown.

**Comment by tomgilder** [comment] 2021-07-23 16:48
Closing this for now as I'm 99% sure it's caused by https://github.com/flutter/flutter/issues/86222

Please comment and I'll be happy to reopen if it isn't.

**Closed by tomgilder** 2021-07-23 16:48 UTC
Labels: bug, question
