### ISSUE TITLE
Cant push or replace same route with new parameters

### ISSUE THREAD

**Issue by M4RZB4Ni** [tomgilder/routemaster#183] opened 2021-07-29 16:45 UTC
Hi
I created a route with a pattern and path parameter
when I push that route and want to reopen the same route with new  path parameters
stack seems to reset and push or replace functions not work and I come back to the home page.

**My main class:**

`  void main() {
   //setPathUrlStrategy();

  runApp(MyApp());
  configLoading();
}
  void configLoading() {

  EasyLoading.instance

    ..indicatorWidget = Image.asset(
      "assets/images/logo_black.png",
      width: 100,
      height: 60,
    )
    ..loadingStyle = EasyLoadingStyle.custom
    ..indicatorSize = 45.0
    ..radius = 10.0
    ..progressColor = Colors.white
    ..backgroundColor = Color(0xffBAA98E)
    ..indicatorColor = Colors.white
    ..textColor = Colors.black87
    ..maskColor = Color(0xff535353)
    ..userInteractions = false
    ..dismissOnTap = false;
}

final routes = RouteMap(
  // onUnknownRoute: (path) {
  //   return MaterialPage(child: Directionality(
  //       textDirection: TextDirection.rtl, child:  MainWeb()));
  // },
  routes: {
    '/': (context) => new MaterialPage(child: Directionality(
        textDirection: TextDirection.rtl, child: MainWeb() )),
    '/Home': (context) => new MaterialPage(child:  Directionality(
        textDirection: TextDirection.rtl, child:  MainWeb())),
  
    '/IdeaView/:idea': (context) => new MaterialPage(child :  Directionality(
        textDirection: TextDirection.rtl, child: new IdeaViewWeb(ideaID: context.pathParameters['idea'],))),

  },
);

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {

    return MaterialApp.router(
  

        routerDelegate: RoutemasterDelegate(routesBuilder: (context) => routes),
       routeInformationParser: RoutemasterParser(),

      title: 'HoHo',
      theme: ThemeData(
        fontFamily: 'iranSans',
        primarySwatch: Colors.blue,
      ),
      debugShowCheckedModeBanner: false,
      builder: EasyLoading.init(),
 
    );
  }

}`

**in the homePage I wrote this code for push _ideaView_ Route:**

` _gotoIdeas(var _id)
  {

    Routemaster.of(context).push('/IdeaView/$_id');

  }`

**and in _IdeaView_ Route for reopening the same route I wrote this code:**

` Routemaster.of(context).replace('/IdeaView/${_moreSamples[index]['_id']}');`

but it seems stack resets and I come back to the homePage route!

**Comment by tomgilder** [comment] 2021-07-31 12:06
Hi, I turned your code into the app below but I couldn't reproduce the problem with Routemaster 0.9.5.

Can you please provide a runnable example showing the problem?

```dart
import 'package:flutter/material.dart';
import 'package:routemaster/routemaster.dart';

void main() {
  runApp(MyApp());
}

final routes = RouteMap(
  routes: {
    '/': (context) => MaterialPage(
          child: MainWeb(),
        ),
    '/IdeaView/:idea': (context) => MaterialPage(
          child: IdeaViewWeb(
            ideaID: int.parse(context.pathParameters['idea']!),
          ),
        ),
  },
);

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerDelegate: RoutemasterDelegate(routesBuilder: (context) => routes),
      routeInformationParser: RoutemasterParser(),
    );
  }
}

class MainWeb extends StatelessWidget {
  const MainWeb({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
          Text('MainWeb'),
          ElevatedButton(
            onPressed: () {
              Routemaster.of(context).push('/IdeaView/1');
            },
            child: Text('Push /IdeaView/1'),
          )
        ],
      ),
    );
  }
}

class IdeaViewWeb extends StatelessWidget {
  final int ideaID;

  const IdeaViewWeb({required this.ideaID});

  @override
  Widget build(BuildContext context) {
    final nextId = ideaID + 1;

    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
          Text('ID $ideaID'),
          ElevatedButton(
            onPressed: () {
              Routemaster.of(context).replace('/IdeaView/$nextId');
            },
            child: Text('Replace /IdeaView/$nextId'),
          )
        ],
      ),
    );
  }
}
```

**Comment by tomgilder** [comment] 2021-08-14 11:52
I can't do anything more with this without reproduction code. Closing for now, please provide a repro and I'll be happy to reopen.

**Closed by tomgilder** 2021-08-14 11:52 UTC
Labels: question

**Comment by Roma-Kmita** [comment] 2022-06-30 10:27
I have same problem. On push from page '/items/2' to '/items/5', push dont work.

**Comment by Roma-Kmita** [comment] 2022-06-30 14:41
I found the solution, just add key to MaterialPage.
` MaterialPage(
  key: UniqueKey(),
  child:...
)`
