### ISSUE TITLE
RoutemasterDelegate routesBuilder rebuilding

### ISSUE THREAD

**Issue by WalidChebaro** [tomgilder/routemaster#162] opened 2021-07-06 09:53 UTC
if you add a print inside routesBuilder you can see that it prints twice thus rebuilding navigation can we fix this in order to make it build only once.

**Comment by tomgilder** [comment] 2021-07-09 15:32
Hi, thanks for the issue, how big a problem is this please?

Is it causing a functionality issue or is it a performance concern?

**Comment by WalidChebaro** [comment] 2021-07-11 07:40
This problem affects performance and stability. it is also obliging me to add a boolean when I access the first page so that I do not target events multiple times. The idea is that you are using change notifier for the routes delegate try to add a new initial builder function for example where you remove notify listeners. This would do the trick as It would be used only for the initial call and then you would use the normal builder later on which would notify the changes in routes.

**Comment by tomgilder** [comment] 2021-07-11 08:11
Could you post an example of the code that's causing this issue please?

Is it just on app start-up that `routesBuilder` is being called twice?

In general you shouldn't rely on `routesBuilder` only being called once, due to the design of Routemaster allowing routes to be swapped at runtime.

You can assign the routing map to a variable and return it, so you're not rebuilding it every time.

**Comment by WalidChebaro** [comment] 2021-07-12 07:24
let's schedule a meeting if possible so that I can show you what I mean it would be easier

**Comment by tomgilder** [comment] 2021-07-18 12:43
Hello, sorry, I'd much prefer a simple repro of the problem if you can. I don't really have time for meetings to support Routemaster currently.

**Comment by tomgilder** [comment] 2021-08-14 11:53
I can't do anything more with this without reproduction code. Closing for now, please provide a repro and I'll be happy to reopen.

**Closed by tomgilder** 2021-08-14 11:53 UTC
Labels: question, need repro
